version: "3.8"

services:
  budgets:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6622:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    stdin_open: true
    tty: true
